feat: Improve DdlRel message
Neuroblade/substrait pull request #1
Opened 2023-05-17 16:19 UTC by moshe-yakovson

add DdlRel to Rel message
add table_metadata field to DdlRel

@DaichikAmir @reutev

2023-05-17 16:52 UTC, DaichikAmir requested changes

2023-05-17 16:52 UTC, DaichikAmir commented on proto/substrait/algebra.proto
> +  // Field that can be used to extend/introduce any target spesific metadata
Specific (typo)

2023-05-17 17:13 UTC, DaichikAmir commented
Looks fine but I think that we can add fields that will probably be accepted , such as primary key

2023-05-18 10:59 UTC, moshe-yakovson commented on proto/substrait/algebra.proto
> +  // any target spesific metadata about the table data
```suggestion
  // any target specific metadata about the table data
```

2023-05-18 11:06 UTC, DaichikAmir approved these changes
Looks good to me , @reutev what do you think?

2023-05-18 11:25 UTC, shaharv commented on proto/substrait/algebra.proto
> +  // like replication, partition etc
```suggestion
  // Field that could be used to extend or introduce any target specific metadata about the table,
  // like replication, partition, etc.
```

2023-05-18 11:27 UTC, shaharv commented on proto/substrait/algebra.proto
> +  // Indexes of all primary keys in the table
```suggestion
  // Indices of all primary keys in the table
```

2023-05-18 11:27 UTC, shaharv commented on proto/substrait/algebra.proto
> +  repeated int32 primary_key = 9;
```suggestion
  repeated int32 primary_keys = 9;
```

2023-05-18 11:44 UTC, merged